### ISSUE TITLE
KDF is weak and does not run in constant time

### ISSUE THREAD

**Issue by atoponce** [kennbr34/passmanager#21]
https://github.com/kennbr34/passmanager/blob/master/src/passmanager.c#L3207

The KDF should not be dependent on the password or salt. The iterations instead should be statically set, regardless of the provided password. The iteration count should also be increased from 1k to 100k.

**Comment by kennbr34** [comment]
I updated to change the default iteration amount to 200k based on your advice of making it take at least a second or longer.  It was taking 1.9 seconds on a 1st gen i5-2520, which probably means more recent hardware would need even more iterations.

I decided to add an option switch so the user could specify an iteration amount. That will also enable a user to custom-tune the iteration amount to take longer on faster hardware, as well as make it non-standard so an attacker will have another variable to guess, but also keep it independent of password length.
